# -*- coding: utf-8 -*-
"""Online_Payment_Fraud_Detection_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUV1RCahK-dOU-8QT9F6D007NfItsfx7
"""

# Import required libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset

df = pd.read_csv("Online_Payment_Fraud_Dataset.csv")

# Preview / Display the dataset

df.head()

# Display dataset information

df.info()

# Check number of rows and columns

df.shape

# Display statistical summary

df.describe()

# Check and handle missing values

df.isnull().sum()

df.fillna(df.mean(numeric_only=True), inplace=True)

# Check and handle duplicate rows

df.duplicated().sum()

df.drop_duplicates(inplace=True)

# Check target column

df['isFraud'].value_counts()

# Separate features and target

X = df.drop(['isFraud',], axis=1)

y = df['isFraud']

# Checking Categorical Columns (before removing IDs)

print(df.select_dtypes(include='object').columns)

# Remove unnecessary ID columns

df = df.drop(["nameOrig", "nameDest"], axis=1, errors="ignore")

# Checking categorical Columns (after removing IDs)

df.select_dtypes(include='object').columns

# Encode categorical data

categorical_columns = X.select_dtypes(include='object').columns

encoder = LabelEncoder()

for column in categorical_columns:
    X[column] = encoder.fit_transform(X[column])

# Feature scaling

feature_names = X.columns

scaler = StandardScaler()

X = scaler.fit_transform(X)

# Split the dataset

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Logistic Regression model

lr_model = LogisticRegression(
    max_iter=10,
    random_state=42
)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, y_pred_lr)

print(f"Accuracy of the Logistic Regression: {lr_accuracy * 100:.2f}%")

# Train Decision Tree model

dt_model = DecisionTreeClassifier(
    max_depth=15,
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print(f"Accuracy of the Decision Tree: {dt_accuracy * 100:.2f}%")

# Train Random Forest model

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print(f"Accuracy of the Random Forest: {rf_accuracy * 100:.2f}%")

# Compare all Models

model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "Accuracy(%)": [
        lr_accuracy * 100,
        dt_accuracy * 100,
        rf_accuracy * 100
    ]
})

model_comparison

# Plot accuracy graph

plt.figure(figsize=(8,5))

sns.barplot(
    x="Model",
    y="Accuracy(%)",
    data=model_comparison
)

plt.title("Model Accuracy Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy(%)")

plt.show()

# Find the best model

best_model = model_comparison.loc[
    model_comparison["Accuracy(%)"].idxmax()
]

print(best_model)

# Selecting Random Forest as the final model

final_model = rf_model

# Creating Confusion Matrix

cm = confusion_matrix(y_test, y_pred_rf)

print(cm)

# Plotting Confusion Matrix

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='coolwarm'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# Display classification report

print(classification_report(y_test, y_pred_rf))

# Calculate feature importance

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": final_model.feature_importances_
})

# Sort feature importance

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance

# Plot feature importance

plt.figure(figsize=(8,5))

sns.barplot(
    x="Importance",
    y="Feature",
    data=feature_importance
)

plt.title("Feature Importance")

plt.show()

# Predict transaction status

def predict_fraud(data):

  prediction = final_model.predict(data)

  return prediction

# Make prediction on test data

prediction = final_model.predict(X_test)

print("Prediction:", prediction[0])

# Display transaction result

if (prediction[0] == 0):
    print("Transaction Status : Legitimate Transaction")

else:
    print("Transaction Status : Fraudulent Transaction")